// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Lambda Go Swagger Test API
//
//  A Test API for testing lambda/go-swagger integration
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /
//  Version: 1.0.0
//  License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html
//  Contact: <sean@gopaddy.ch>
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
