// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "swagger": "2.0",
  "info": {
    "description": "A Test API for testing lambda/go-swagger integration",
    "title": "Test API",
    "contact": {
      "email": "sean@gopaddy.ch"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "1.0.0"
  },
  "paths": {
    "/test": {
      "get": {
        "description": "An endpoint for testing",
        "produces": [
          "application/json"
        ],
        "tags": [
          "open"
        ],
        "summary": "Gets test endpoint",
        "operationId": "getTestEndpoint",
        "responses": {
          "200": {
            "description": "Test Response",
            "schema": {
              "$ref": "#/definitions/TestResponse"
            }
          },
          "500": {
            "description": "General Failure"
          }
        },
        "x-amazon-apigateway-integration": {
          "httpMethod": "post",
          "type": "aws_proxy",
          "uri": {
            "Fn::Sub": "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaSwaggerTestFunction.Arn}/invocations"
          }
        }
      }
    },
    "/test/alternative": {
      "get": {
        "description": "An alternative endpoint for testing",
        "produces": [
          "application/json"
        ],
        "tags": [
          "open"
        ],
        "summary": "Gets test endpoint",
        "operationId": "getAlternativeTestEndpoint",
        "responses": {
          "200": {
            "description": "Test Response",
            "schema": {
              "$ref": "#/definitions/TestResponse"
            }
          },
          "500": {
            "description": "General Failure"
          }
        },
        "x-amazon-apigateway-integration": {
          "httpMethod": "post",
          "type": "aws_proxy",
          "uri": {
            "Fn::Sub": "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaSwaggerTestFunction.Arn}/invocations"
          }
        }
      }
    },
    "/test/with-param/{param}": {
      "get": {
        "description": "An alternative endpoint for testing",
        "produces": [
          "application/json"
        ],
        "tags": [
          "open"
        ],
        "summary": "Gets test endpoint",
        "operationId": "getTestWithParameterEndpoint",
        "parameters": [
          {
            "type": "string",
            "description": "Test Parameter",
            "name": "param",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Test Response",
            "schema": {
              "$ref": "#/definitions/TestResponse"
            }
          },
          "500": {
            "description": "General Failure"
          }
        },
        "x-amazon-apigateway-integration": {
          "httpMethod": "post",
          "type": "aws_proxy",
          "uri": {
            "Fn::Sub": "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaSwaggerTestFunction.Arn}/invocations"
          }
        }
      }
    }
  },
  "definitions": {
    "TestResponse": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "message": {
          "type": "string"
        }
      }
    }
  },
  "tags": [
    {
      "description": "Calls which are open to anyone",
      "name": "open"
    }
  ]
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "swagger": "2.0",
  "info": {
    "description": "A Test API for testing lambda/go-swagger integration",
    "title": "Test API",
    "contact": {
      "email": "sean@gopaddy.ch"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "1.0.0"
  },
  "paths": {
    "/test": {
      "get": {
        "description": "An endpoint for testing",
        "produces": [
          "application/json"
        ],
        "tags": [
          "open"
        ],
        "summary": "Gets test endpoint",
        "operationId": "getTestEndpoint",
        "responses": {
          "200": {
            "description": "Test Response",
            "schema": {
              "$ref": "#/definitions/TestResponse"
            }
          },
          "500": {
            "description": "General Failure"
          }
        },
        "x-amazon-apigateway-integration": {
          "httpMethod": "post",
          "type": "aws_proxy",
          "uri": {
            "Fn::Sub": "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaSwaggerTestFunction.Arn}/invocations"
          }
        }
      }
    },
    "/test/alternative": {
      "get": {
        "description": "An alternative endpoint for testing",
        "produces": [
          "application/json"
        ],
        "tags": [
          "open"
        ],
        "summary": "Gets test endpoint",
        "operationId": "getAlternativeTestEndpoint",
        "responses": {
          "200": {
            "description": "Test Response",
            "schema": {
              "$ref": "#/definitions/TestResponse"
            }
          },
          "500": {
            "description": "General Failure"
          }
        },
        "x-amazon-apigateway-integration": {
          "httpMethod": "post",
          "type": "aws_proxy",
          "uri": {
            "Fn::Sub": "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaSwaggerTestFunction.Arn}/invocations"
          }
        }
      }
    },
    "/test/with-param/{param}": {
      "get": {
        "description": "An alternative endpoint for testing",
        "produces": [
          "application/json"
        ],
        "tags": [
          "open"
        ],
        "summary": "Gets test endpoint",
        "operationId": "getTestWithParameterEndpoint",
        "parameters": [
          {
            "type": "string",
            "description": "Test Parameter",
            "name": "param",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Test Response",
            "schema": {
              "$ref": "#/definitions/TestResponse"
            }
          },
          "500": {
            "description": "General Failure"
          }
        },
        "x-amazon-apigateway-integration": {
          "httpMethod": "post",
          "type": "aws_proxy",
          "uri": {
            "Fn::Sub": "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaSwaggerTestFunction.Arn}/invocations"
          }
        }
      }
    }
  },
  "definitions": {
    "TestResponse": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "message": {
          "type": "string"
        }
      }
    }
  },
  "tags": [
    {
      "description": "Calls which are open to anyone",
      "name": "open"
    }
  ]
}`))
}
