AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-swagger-test

  SAM Template for simple application to demonstrate use of go-swagger on Lambda.

Resources:
  LambdaSwaggerTestAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: test

      # Allows www.example.com to call these APIs
      # SAM will automatically add AllowMethods with a list of methods for this API
      #Cors: "'www.example.com'"

      DefinitionBody:
        'Fn::Transform':
          Name: 'AWS::Include'
          # Replace <bucket> with your bucket name
          Parameters:
            Location: ../swagger.yaml

  LambdaSwaggerTestFunction:
    Type: AWS::Serverless::Function
    Properties:
      # Replace <bucket> with your bucket name
      CodeUri: ./lambda-swagger-test.zip
      Handler: lambda-swagger-test
      Runtime: go1.x
      Events:
        ProxyApiRoot:
          Type: Api
          Properties:
            RestApiId: !Ref LambdaSwaggerTestAPI
            Path: /
            Method: ANY
        ProxyApiGreedy:
          Type: Api
          Properties:
            RestApiId: !Ref LambdaSwaggerTestAPI
            Path: /{proxy+}
            Method: ANY

Outputs:
  LambdaSwaggerTestFunctionArn:
    Description: "REST API Handler function"
    Value: !GetAtt LambdaSwaggerTestFunction.Arn

  LambdaSwaggerTestAPIArn:
    Description: "The endpoint to connect to the REST API (staging)"
    #Value: !GetAtt TravelUpdateAPI.Arn
    Value: !Join [ '', [ 'https://', !Ref LambdaSwaggerTestAPI, '.execute-api.',!Ref 'AWS::Region','.amazonaws.com/staging'] ]

