// Code generated by go-swagger; DO NOT EDIT.

package open

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/seanrmurphy/lambda-swagger-test/models"
)

// GetBodyParamSimpleResponseInternalServerErrorCode is the HTTP code returned for type GetBodyParamSimpleResponseInternalServerError
const GetBodyParamSimpleResponseInternalServerErrorCode int = 500

/*GetBodyParamSimpleResponseInternalServerError General Failure

swagger:response getBodyParamSimpleResponseInternalServerError
*/
type GetBodyParamSimpleResponseInternalServerError struct {
}

// NewGetBodyParamSimpleResponseInternalServerError creates GetBodyParamSimpleResponseInternalServerError with default headers values
func NewGetBodyParamSimpleResponseInternalServerError() *GetBodyParamSimpleResponseInternalServerError {

	return &GetBodyParamSimpleResponseInternalServerError{}
}

// WriteResponse to the client
func (o *GetBodyParamSimpleResponseInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}

// GetBodyParamSimpleResponseNotImplementedCode is the HTTP code returned for type GetBodyParamSimpleResponseNotImplemented
const GetBodyParamSimpleResponseNotImplementedCode int = 501

/*GetBodyParamSimpleResponseNotImplemented API call runs, but there is no implementation

swagger:response getBodyParamSimpleResponseNotImplemented
*/
type GetBodyParamSimpleResponseNotImplemented struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewGetBodyParamSimpleResponseNotImplemented creates GetBodyParamSimpleResponseNotImplemented with default headers values
func NewGetBodyParamSimpleResponseNotImplemented() *GetBodyParamSimpleResponseNotImplemented {

	return &GetBodyParamSimpleResponseNotImplemented{}
}

// WithPayload adds the payload to the get body param simple response not implemented response
func (o *GetBodyParamSimpleResponseNotImplemented) WithPayload(payload *models.ErrorResponse) *GetBodyParamSimpleResponseNotImplemented {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get body param simple response not implemented response
func (o *GetBodyParamSimpleResponseNotImplemented) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBodyParamSimpleResponseNotImplemented) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(501)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
