// Code generated by go-swagger; DO NOT EDIT.

package open

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/seanrmurphy/lambda-swagger-test/models"
)

// GetBodyParamEmptyResponseInternalServerErrorCode is the HTTP code returned for type GetBodyParamEmptyResponseInternalServerError
const GetBodyParamEmptyResponseInternalServerErrorCode int = 500

/*GetBodyParamEmptyResponseInternalServerError General Failure

swagger:response getBodyParamEmptyResponseInternalServerError
*/
type GetBodyParamEmptyResponseInternalServerError struct {
}

// NewGetBodyParamEmptyResponseInternalServerError creates GetBodyParamEmptyResponseInternalServerError with default headers values
func NewGetBodyParamEmptyResponseInternalServerError() *GetBodyParamEmptyResponseInternalServerError {

	return &GetBodyParamEmptyResponseInternalServerError{}
}

// WriteResponse to the client
func (o *GetBodyParamEmptyResponseInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}

// GetBodyParamEmptyResponseNotImplementedCode is the HTTP code returned for type GetBodyParamEmptyResponseNotImplemented
const GetBodyParamEmptyResponseNotImplementedCode int = 501

/*GetBodyParamEmptyResponseNotImplemented API call runs, but there is no implementation

swagger:response getBodyParamEmptyResponseNotImplemented
*/
type GetBodyParamEmptyResponseNotImplemented struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewGetBodyParamEmptyResponseNotImplemented creates GetBodyParamEmptyResponseNotImplemented with default headers values
func NewGetBodyParamEmptyResponseNotImplemented() *GetBodyParamEmptyResponseNotImplemented {

	return &GetBodyParamEmptyResponseNotImplemented{}
}

// WithPayload adds the payload to the get body param empty response not implemented response
func (o *GetBodyParamEmptyResponseNotImplemented) WithPayload(payload *models.ErrorResponse) *GetBodyParamEmptyResponseNotImplemented {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get body param empty response not implemented response
func (o *GetBodyParamEmptyResponseNotImplemented) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBodyParamEmptyResponseNotImplemented) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(501)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
