// Code generated by go-swagger; DO NOT EDIT.

package open

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetPathParamErrorResponseHandlerFunc turns a function with the right signature into a get path param error response handler
type GetPathParamErrorResponseHandlerFunc func(GetPathParamErrorResponseParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetPathParamErrorResponseHandlerFunc) Handle(params GetPathParamErrorResponseParams) middleware.Responder {
	return fn(params)
}

// GetPathParamErrorResponseHandler interface for that can handle valid get path param error response params
type GetPathParamErrorResponseHandler interface {
	Handle(GetPathParamErrorResponseParams) middleware.Responder
}

// NewGetPathParamErrorResponse creates a new http.Handler for the get path param error response operation
func NewGetPathParamErrorResponse(ctx *middleware.Context, handler GetPathParamErrorResponseHandler) *GetPathParamErrorResponse {
	return &GetPathParamErrorResponse{Context: ctx, Handler: handler}
}

/*GetPathParamErrorResponse swagger:route GET /path-param/error-response/{param} open getPathParamErrorResponse

An endpoint which takes an input parameter and returns a HTTP response code and an error response

An endpoint which takes an input parameter and returns a HTTP response code and an error response

*/
type GetPathParamErrorResponse struct {
	Context *middleware.Context
	Handler GetPathParamErrorResponseHandler
}

func (o *GetPathParamErrorResponse) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetPathParamErrorResponseParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
