// Code generated by go-swagger; DO NOT EDIT.

package open

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetNoParamsErrorResponseHandlerFunc turns a function with the right signature into a get no params error response handler
type GetNoParamsErrorResponseHandlerFunc func(GetNoParamsErrorResponseParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetNoParamsErrorResponseHandlerFunc) Handle(params GetNoParamsErrorResponseParams) middleware.Responder {
	return fn(params)
}

// GetNoParamsErrorResponseHandler interface for that can handle valid get no params error response params
type GetNoParamsErrorResponseHandler interface {
	Handle(GetNoParamsErrorResponseParams) middleware.Responder
}

// NewGetNoParamsErrorResponse creates a new http.Handler for the get no params error response operation
func NewGetNoParamsErrorResponse(ctx *middleware.Context, handler GetNoParamsErrorResponseHandler) *GetNoParamsErrorResponse {
	return &GetNoParamsErrorResponse{Context: ctx, Handler: handler}
}

/*GetNoParamsErrorResponse swagger:route GET /no-params/error-response open getNoParamsErrorResponse

An endpoint which returns a HTTP response code and an error response

An endpoint which returns a HTTP response code and an error response

*/
type GetNoParamsErrorResponse struct {
	Context *middleware.Context
	Handler GetNoParamsErrorResponseHandler
}

func (o *GetNoParamsErrorResponse) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetNoParamsErrorResponseParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
