// Code generated by go-swagger; DO NOT EDIT.

package open

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/seanrmurphy/lambda-swagger-test/models"
)

// GetNoParamsComplexResponseOKCode is the HTTP code returned for type GetNoParamsComplexResponseOK
const GetNoParamsComplexResponseOKCode int = 200

/*GetNoParamsComplexResponseOK Successful execution of API call returning complex object

swagger:response getNoParamsComplexResponseOK
*/
type GetNoParamsComplexResponseOK struct {

	/*
	  In: Body
	*/
	Payload *models.ComplexObjectResponse `json:"body,omitempty"`
}

// NewGetNoParamsComplexResponseOK creates GetNoParamsComplexResponseOK with default headers values
func NewGetNoParamsComplexResponseOK() *GetNoParamsComplexResponseOK {

	return &GetNoParamsComplexResponseOK{}
}

// WithPayload adds the payload to the get no params complex response o k response
func (o *GetNoParamsComplexResponseOK) WithPayload(payload *models.ComplexObjectResponse) *GetNoParamsComplexResponseOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get no params complex response o k response
func (o *GetNoParamsComplexResponseOK) SetPayload(payload *models.ComplexObjectResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetNoParamsComplexResponseOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetNoParamsComplexResponseInternalServerErrorCode is the HTTP code returned for type GetNoParamsComplexResponseInternalServerError
const GetNoParamsComplexResponseInternalServerErrorCode int = 500

/*GetNoParamsComplexResponseInternalServerError General Failure

swagger:response getNoParamsComplexResponseInternalServerError
*/
type GetNoParamsComplexResponseInternalServerError struct {
}

// NewGetNoParamsComplexResponseInternalServerError creates GetNoParamsComplexResponseInternalServerError with default headers values
func NewGetNoParamsComplexResponseInternalServerError() *GetNoParamsComplexResponseInternalServerError {

	return &GetNoParamsComplexResponseInternalServerError{}
}

// WriteResponse to the client
func (o *GetNoParamsComplexResponseInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
