// Code generated by go-swagger; DO NOT EDIT.

package open

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetBodyParamComplexResponseHandlerFunc turns a function with the right signature into a get body param complex response handler
type GetBodyParamComplexResponseHandlerFunc func(GetBodyParamComplexResponseParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetBodyParamComplexResponseHandlerFunc) Handle(params GetBodyParamComplexResponseParams) middleware.Responder {
	return fn(params)
}

// GetBodyParamComplexResponseHandler interface for that can handle valid get body param complex response params
type GetBodyParamComplexResponseHandler interface {
	Handle(GetBodyParamComplexResponseParams) middleware.Responder
}

// NewGetBodyParamComplexResponse creates a new http.Handler for the get body param complex response operation
func NewGetBodyParamComplexResponse(ctx *middleware.Context, handler GetBodyParamComplexResponseHandler) *GetBodyParamComplexResponse {
	return &GetBodyParamComplexResponse{Context: ctx, Handler: handler}
}

/*GetBodyParamComplexResponse swagger:route GET /body-param/complex-response open getBodyParamComplexResponse

Get endpoint defined which simply gives response indicating that POST should be used

Get endpoint defined which simply gives response indicating that POST should be used

*/
type GetBodyParamComplexResponse struct {
	Context *middleware.Context
	Handler GetBodyParamComplexResponseHandler
}

func (o *GetBodyParamComplexResponse) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetBodyParamComplexResponseParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
