// Code generated by go-swagger; DO NOT EDIT.

package open

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/seanrmurphy/lambda-swagger-test/models"
)

// GetPathParamSimpleResponseOKCode is the HTTP code returned for type GetPathParamSimpleResponseOK
const GetPathParamSimpleResponseOKCode int = 200

/*GetPathParamSimpleResponseOK Successful execution of API call returning message in simple JSON object

swagger:response getPathParamSimpleResponseOK
*/
type GetPathParamSimpleResponseOK struct {

	/*
	  In: Body
	*/
	Payload *models.SimpleMessageResponse `json:"body,omitempty"`
}

// NewGetPathParamSimpleResponseOK creates GetPathParamSimpleResponseOK with default headers values
func NewGetPathParamSimpleResponseOK() *GetPathParamSimpleResponseOK {

	return &GetPathParamSimpleResponseOK{}
}

// WithPayload adds the payload to the get path param simple response o k response
func (o *GetPathParamSimpleResponseOK) WithPayload(payload *models.SimpleMessageResponse) *GetPathParamSimpleResponseOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get path param simple response o k response
func (o *GetPathParamSimpleResponseOK) SetPayload(payload *models.SimpleMessageResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPathParamSimpleResponseOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetPathParamSimpleResponseInternalServerErrorCode is the HTTP code returned for type GetPathParamSimpleResponseInternalServerError
const GetPathParamSimpleResponseInternalServerErrorCode int = 500

/*GetPathParamSimpleResponseInternalServerError General Failure

swagger:response getPathParamSimpleResponseInternalServerError
*/
type GetPathParamSimpleResponseInternalServerError struct {
}

// NewGetPathParamSimpleResponseInternalServerError creates GetPathParamSimpleResponseInternalServerError with default headers values
func NewGetPathParamSimpleResponseInternalServerError() *GetPathParamSimpleResponseInternalServerError {

	return &GetPathParamSimpleResponseInternalServerError{}
}

// WriteResponse to the client
func (o *GetPathParamSimpleResponseInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
