// Code generated by go-swagger; DO NOT EDIT.

package open

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/seanrmurphy/lambda-swagger-test/models"
)

// GetBodyParamComplexResponseInternalServerErrorCode is the HTTP code returned for type GetBodyParamComplexResponseInternalServerError
const GetBodyParamComplexResponseInternalServerErrorCode int = 500

/*GetBodyParamComplexResponseInternalServerError General Failure

swagger:response getBodyParamComplexResponseInternalServerError
*/
type GetBodyParamComplexResponseInternalServerError struct {
}

// NewGetBodyParamComplexResponseInternalServerError creates GetBodyParamComplexResponseInternalServerError with default headers values
func NewGetBodyParamComplexResponseInternalServerError() *GetBodyParamComplexResponseInternalServerError {

	return &GetBodyParamComplexResponseInternalServerError{}
}

// WriteResponse to the client
func (o *GetBodyParamComplexResponseInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}

// GetBodyParamComplexResponseNotImplementedCode is the HTTP code returned for type GetBodyParamComplexResponseNotImplemented
const GetBodyParamComplexResponseNotImplementedCode int = 501

/*GetBodyParamComplexResponseNotImplemented API call runs, but there is no implementation

swagger:response getBodyParamComplexResponseNotImplemented
*/
type GetBodyParamComplexResponseNotImplemented struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewGetBodyParamComplexResponseNotImplemented creates GetBodyParamComplexResponseNotImplemented with default headers values
func NewGetBodyParamComplexResponseNotImplemented() *GetBodyParamComplexResponseNotImplemented {

	return &GetBodyParamComplexResponseNotImplemented{}
}

// WithPayload adds the payload to the get body param complex response not implemented response
func (o *GetBodyParamComplexResponseNotImplemented) WithPayload(payload *models.ErrorResponse) *GetBodyParamComplexResponseNotImplemented {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get body param complex response not implemented response
func (o *GetBodyParamComplexResponseNotImplemented) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBodyParamComplexResponseNotImplemented) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(501)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
