// Code generated by go-swagger; DO NOT EDIT.

package open

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewGetPathParamEmptyResponseParams creates a new GetPathParamEmptyResponseParams object
// no default values defined in spec.
func NewGetPathParamEmptyResponseParams() GetPathParamEmptyResponseParams {

	return GetPathParamEmptyResponseParams{}
}

// GetPathParamEmptyResponseParams contains all the bound params for the get path param empty response operation
// typically these are obtained from a http.Request
//
// swagger:parameters getPathParamEmptyResponse
type GetPathParamEmptyResponseParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*An arbitrary test parameter which is ignored here
	  Required: true
	  In: path
	*/
	Param string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetPathParamEmptyResponseParams() beforehand.
func (o *GetPathParamEmptyResponseParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rParam, rhkParam, _ := route.Params.GetOK("param")
	if err := o.bindParam(rParam, rhkParam, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindParam binds and validates parameter Param from path.
func (o *GetPathParamEmptyResponseParams) bindParam(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.Param = raw

	return nil
}
