// Code generated by go-swagger; DO NOT EDIT.

package open

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetBodyParamSimpleResponseHandlerFunc turns a function with the right signature into a get body param simple response handler
type GetBodyParamSimpleResponseHandlerFunc func(GetBodyParamSimpleResponseParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetBodyParamSimpleResponseHandlerFunc) Handle(params GetBodyParamSimpleResponseParams) middleware.Responder {
	return fn(params)
}

// GetBodyParamSimpleResponseHandler interface for that can handle valid get body param simple response params
type GetBodyParamSimpleResponseHandler interface {
	Handle(GetBodyParamSimpleResponseParams) middleware.Responder
}

// NewGetBodyParamSimpleResponse creates a new http.Handler for the get body param simple response operation
func NewGetBodyParamSimpleResponse(ctx *middleware.Context, handler GetBodyParamSimpleResponseHandler) *GetBodyParamSimpleResponse {
	return &GetBodyParamSimpleResponse{Context: ctx, Handler: handler}
}

/*GetBodyParamSimpleResponse swagger:route GET /body-param/simple-response open getBodyParamSimpleResponse

Get endpoint defined which simply gives response indicating that POST should be used

Get endpoint defined which simply gives response indicating that POST should be used

*/
type GetBodyParamSimpleResponse struct {
	Context *middleware.Context
	Handler GetBodyParamSimpleResponseHandler
}

func (o *GetBodyParamSimpleResponse) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetBodyParamSimpleResponseParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
