// Code generated by go-swagger; DO NOT EDIT.

package open

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/seanrmurphy/lambda-swagger-test/models"
)

// GetBodyParamErrorResponseOKCode is the HTTP code returned for type GetBodyParamErrorResponseOK
const GetBodyParamErrorResponseOKCode int = 200

/*GetBodyParamErrorResponseOK Successful execution of API call

swagger:response getBodyParamErrorResponseOK
*/
type GetBodyParamErrorResponseOK struct {

	/*
	  In: Body
	*/
	Payload *models.SimpleMessageResponse `json:"body,omitempty"`
}

// NewGetBodyParamErrorResponseOK creates GetBodyParamErrorResponseOK with default headers values
func NewGetBodyParamErrorResponseOK() *GetBodyParamErrorResponseOK {

	return &GetBodyParamErrorResponseOK{}
}

// WithPayload adds the payload to the get body param error response o k response
func (o *GetBodyParamErrorResponseOK) WithPayload(payload *models.SimpleMessageResponse) *GetBodyParamErrorResponseOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get body param error response o k response
func (o *GetBodyParamErrorResponseOK) SetPayload(payload *models.SimpleMessageResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBodyParamErrorResponseOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetBodyParamErrorResponseInternalServerErrorCode is the HTTP code returned for type GetBodyParamErrorResponseInternalServerError
const GetBodyParamErrorResponseInternalServerErrorCode int = 500

/*GetBodyParamErrorResponseInternalServerError General Failure

swagger:response getBodyParamErrorResponseInternalServerError
*/
type GetBodyParamErrorResponseInternalServerError struct {
}

// NewGetBodyParamErrorResponseInternalServerError creates GetBodyParamErrorResponseInternalServerError with default headers values
func NewGetBodyParamErrorResponseInternalServerError() *GetBodyParamErrorResponseInternalServerError {

	return &GetBodyParamErrorResponseInternalServerError{}
}

// WriteResponse to the client
func (o *GetBodyParamErrorResponseInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
