// Code generated by go-swagger; DO NOT EDIT.

package open

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/seanrmurphy/lambda-swagger-test/models"
)

// GetBodyParamErrorResponseInternalServerErrorCode is the HTTP code returned for type GetBodyParamErrorResponseInternalServerError
const GetBodyParamErrorResponseInternalServerErrorCode int = 500

/*GetBodyParamErrorResponseInternalServerError General Failure

swagger:response getBodyParamErrorResponseInternalServerError
*/
type GetBodyParamErrorResponseInternalServerError struct {
}

// NewGetBodyParamErrorResponseInternalServerError creates GetBodyParamErrorResponseInternalServerError with default headers values
func NewGetBodyParamErrorResponseInternalServerError() *GetBodyParamErrorResponseInternalServerError {

	return &GetBodyParamErrorResponseInternalServerError{}
}

// WriteResponse to the client
func (o *GetBodyParamErrorResponseInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}

// GetBodyParamErrorResponseNotImplementedCode is the HTTP code returned for type GetBodyParamErrorResponseNotImplemented
const GetBodyParamErrorResponseNotImplementedCode int = 501

/*GetBodyParamErrorResponseNotImplemented API call runs, but there is no implementation

swagger:response getBodyParamErrorResponseNotImplemented
*/
type GetBodyParamErrorResponseNotImplemented struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewGetBodyParamErrorResponseNotImplemented creates GetBodyParamErrorResponseNotImplemented with default headers values
func NewGetBodyParamErrorResponseNotImplemented() *GetBodyParamErrorResponseNotImplemented {

	return &GetBodyParamErrorResponseNotImplemented{}
}

// WithPayload adds the payload to the get body param error response not implemented response
func (o *GetBodyParamErrorResponseNotImplemented) WithPayload(payload *models.ErrorResponse) *GetBodyParamErrorResponseNotImplemented {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get body param error response not implemented response
func (o *GetBodyParamErrorResponseNotImplemented) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBodyParamErrorResponseNotImplemented) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(501)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
