// Code generated by go-swagger; DO NOT EDIT.

package open

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/seanrmurphy/lambda-swagger-test/models"
)

// GetPathParamComplexResponseOKCode is the HTTP code returned for type GetPathParamComplexResponseOK
const GetPathParamComplexResponseOKCode int = 200

/*GetPathParamComplexResponseOK Successful execution of API call returning complex object

swagger:response getPathParamComplexResponseOK
*/
type GetPathParamComplexResponseOK struct {

	/*
	  In: Body
	*/
	Payload *models.ComplexObjectResponse `json:"body,omitempty"`
}

// NewGetPathParamComplexResponseOK creates GetPathParamComplexResponseOK with default headers values
func NewGetPathParamComplexResponseOK() *GetPathParamComplexResponseOK {

	return &GetPathParamComplexResponseOK{}
}

// WithPayload adds the payload to the get path param complex response o k response
func (o *GetPathParamComplexResponseOK) WithPayload(payload *models.ComplexObjectResponse) *GetPathParamComplexResponseOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get path param complex response o k response
func (o *GetPathParamComplexResponseOK) SetPayload(payload *models.ComplexObjectResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPathParamComplexResponseOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetPathParamComplexResponseInternalServerErrorCode is the HTTP code returned for type GetPathParamComplexResponseInternalServerError
const GetPathParamComplexResponseInternalServerErrorCode int = 500

/*GetPathParamComplexResponseInternalServerError General Failure

swagger:response getPathParamComplexResponseInternalServerError
*/
type GetPathParamComplexResponseInternalServerError struct {
}

// NewGetPathParamComplexResponseInternalServerError creates GetPathParamComplexResponseInternalServerError with default headers values
func NewGetPathParamComplexResponseInternalServerError() *GetPathParamComplexResponseInternalServerError {

	return &GetPathParamComplexResponseInternalServerError{}
}

// WriteResponse to the client
func (o *GetPathParamComplexResponseInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
