// Code generated by go-swagger; DO NOT EDIT.

package open

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/seanrmurphy/lambda-swagger-test/models"
)

// GetNoParamsSimpleResponseOKCode is the HTTP code returned for type GetNoParamsSimpleResponseOK
const GetNoParamsSimpleResponseOKCode int = 200

/*GetNoParamsSimpleResponseOK Successful execution of API call returning message in simple JSON object

swagger:response getNoParamsSimpleResponseOK
*/
type GetNoParamsSimpleResponseOK struct {

	/*
	  In: Body
	*/
	Payload *models.SimpleMessageResponse `json:"body,omitempty"`
}

// NewGetNoParamsSimpleResponseOK creates GetNoParamsSimpleResponseOK with default headers values
func NewGetNoParamsSimpleResponseOK() *GetNoParamsSimpleResponseOK {

	return &GetNoParamsSimpleResponseOK{}
}

// WithPayload adds the payload to the get no params simple response o k response
func (o *GetNoParamsSimpleResponseOK) WithPayload(payload *models.SimpleMessageResponse) *GetNoParamsSimpleResponseOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get no params simple response o k response
func (o *GetNoParamsSimpleResponseOK) SetPayload(payload *models.SimpleMessageResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetNoParamsSimpleResponseOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetNoParamsSimpleResponseInternalServerErrorCode is the HTTP code returned for type GetNoParamsSimpleResponseInternalServerError
const GetNoParamsSimpleResponseInternalServerErrorCode int = 500

/*GetNoParamsSimpleResponseInternalServerError General Failure

swagger:response getNoParamsSimpleResponseInternalServerError
*/
type GetNoParamsSimpleResponseInternalServerError struct {
}

// NewGetNoParamsSimpleResponseInternalServerError creates GetNoParamsSimpleResponseInternalServerError with default headers values
func NewGetNoParamsSimpleResponseInternalServerError() *GetNoParamsSimpleResponseInternalServerError {

	return &GetNoParamsSimpleResponseInternalServerError{}
}

// WriteResponse to the client
func (o *GetNoParamsSimpleResponseInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
