// Code generated by go-swagger; DO NOT EDIT.

package open

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/seanrmurphy/lambda-swagger-test/models"
)

// GetBodyParamComplexResponseOKCode is the HTTP code returned for type GetBodyParamComplexResponseOK
const GetBodyParamComplexResponseOKCode int = 200

/*GetBodyParamComplexResponseOK Successful execution of API call

swagger:response getBodyParamComplexResponseOK
*/
type GetBodyParamComplexResponseOK struct {

	/*
	  In: Body
	*/
	Payload *models.SimpleMessageResponse `json:"body,omitempty"`
}

// NewGetBodyParamComplexResponseOK creates GetBodyParamComplexResponseOK with default headers values
func NewGetBodyParamComplexResponseOK() *GetBodyParamComplexResponseOK {

	return &GetBodyParamComplexResponseOK{}
}

// WithPayload adds the payload to the get body param complex response o k response
func (o *GetBodyParamComplexResponseOK) WithPayload(payload *models.SimpleMessageResponse) *GetBodyParamComplexResponseOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get body param complex response o k response
func (o *GetBodyParamComplexResponseOK) SetPayload(payload *models.SimpleMessageResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBodyParamComplexResponseOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetBodyParamComplexResponseInternalServerErrorCode is the HTTP code returned for type GetBodyParamComplexResponseInternalServerError
const GetBodyParamComplexResponseInternalServerErrorCode int = 500

/*GetBodyParamComplexResponseInternalServerError General Failure

swagger:response getBodyParamComplexResponseInternalServerError
*/
type GetBodyParamComplexResponseInternalServerError struct {
}

// NewGetBodyParamComplexResponseInternalServerError creates GetBodyParamComplexResponseInternalServerError with default headers values
func NewGetBodyParamComplexResponseInternalServerError() *GetBodyParamComplexResponseInternalServerError {

	return &GetBodyParamComplexResponseInternalServerError{}
}

// WriteResponse to the client
func (o *GetBodyParamComplexResponseInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
