// Code generated by go-swagger; DO NOT EDIT.

package open

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/seanrmurphy/lambda-swagger-test/models"
)

// GetTestWithParameterEndpointOKCode is the HTTP code returned for type GetTestWithParameterEndpointOK
const GetTestWithParameterEndpointOKCode int = 200

/*GetTestWithParameterEndpointOK Test Response

swagger:response getTestWithParameterEndpointOK
*/
type GetTestWithParameterEndpointOK struct {

	/*
	  In: Body
	*/
	Payload *models.TestResponse `json:"body,omitempty"`
}

// NewGetTestWithParameterEndpointOK creates GetTestWithParameterEndpointOK with default headers values
func NewGetTestWithParameterEndpointOK() *GetTestWithParameterEndpointOK {

	return &GetTestWithParameterEndpointOK{}
}

// WithPayload adds the payload to the get test with parameter endpoint o k response
func (o *GetTestWithParameterEndpointOK) WithPayload(payload *models.TestResponse) *GetTestWithParameterEndpointOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get test with parameter endpoint o k response
func (o *GetTestWithParameterEndpointOK) SetPayload(payload *models.TestResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTestWithParameterEndpointOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetTestWithParameterEndpointInternalServerErrorCode is the HTTP code returned for type GetTestWithParameterEndpointInternalServerError
const GetTestWithParameterEndpointInternalServerErrorCode int = 500

/*GetTestWithParameterEndpointInternalServerError General Failure

swagger:response getTestWithParameterEndpointInternalServerError
*/
type GetTestWithParameterEndpointInternalServerError struct {
}

// NewGetTestWithParameterEndpointInternalServerError creates GetTestWithParameterEndpointInternalServerError with default headers values
func NewGetTestWithParameterEndpointInternalServerError() *GetTestWithParameterEndpointInternalServerError {

	return &GetTestWithParameterEndpointInternalServerError{}
}

// WriteResponse to the client
func (o *GetTestWithParameterEndpointInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
