// Code generated by go-swagger; DO NOT EDIT.

package open

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/seanrmurphy/lambda-swagger-test/models"
)

// GetNoParamsErrorResponseIMATeapotCode is the HTTP code returned for type GetNoParamsErrorResponseIMATeapot
const GetNoParamsErrorResponseIMATeapotCode int = 418

/*GetNoParamsErrorResponseIMATeapot Error generated when executing API call

swagger:response getNoParamsErrorResponseIMATeapot
*/
type GetNoParamsErrorResponseIMATeapot struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewGetNoParamsErrorResponseIMATeapot creates GetNoParamsErrorResponseIMATeapot with default headers values
func NewGetNoParamsErrorResponseIMATeapot() *GetNoParamsErrorResponseIMATeapot {

	return &GetNoParamsErrorResponseIMATeapot{}
}

// WithPayload adds the payload to the get no params error response i m a teapot response
func (o *GetNoParamsErrorResponseIMATeapot) WithPayload(payload *models.ErrorResponse) *GetNoParamsErrorResponseIMATeapot {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get no params error response i m a teapot response
func (o *GetNoParamsErrorResponseIMATeapot) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetNoParamsErrorResponseIMATeapot) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(418)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetNoParamsErrorResponseInternalServerErrorCode is the HTTP code returned for type GetNoParamsErrorResponseInternalServerError
const GetNoParamsErrorResponseInternalServerErrorCode int = 500

/*GetNoParamsErrorResponseInternalServerError General Failure

swagger:response getNoParamsErrorResponseInternalServerError
*/
type GetNoParamsErrorResponseInternalServerError struct {
}

// NewGetNoParamsErrorResponseInternalServerError creates GetNoParamsErrorResponseInternalServerError with default headers values
func NewGetNoParamsErrorResponseInternalServerError() *GetNoParamsErrorResponseInternalServerError {

	return &GetNoParamsErrorResponseInternalServerError{}
}

// WriteResponse to the client
func (o *GetNoParamsErrorResponseInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
