// Code generated by go-swagger; DO NOT EDIT.

package open

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetNoParamsEmptyResponseOKCode is the HTTP code returned for type GetNoParamsEmptyResponseOK
const GetNoParamsEmptyResponseOKCode int = 200

/*GetNoParamsEmptyResponseOK Successful execution of API call

swagger:response getNoParamsEmptyResponseOK
*/
type GetNoParamsEmptyResponseOK struct {
}

// NewGetNoParamsEmptyResponseOK creates GetNoParamsEmptyResponseOK with default headers values
func NewGetNoParamsEmptyResponseOK() *GetNoParamsEmptyResponseOK {

	return &GetNoParamsEmptyResponseOK{}
}

// WriteResponse to the client
func (o *GetNoParamsEmptyResponseOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// GetNoParamsEmptyResponseInternalServerErrorCode is the HTTP code returned for type GetNoParamsEmptyResponseInternalServerError
const GetNoParamsEmptyResponseInternalServerErrorCode int = 500

/*GetNoParamsEmptyResponseInternalServerError General Failure

swagger:response getNoParamsEmptyResponseInternalServerError
*/
type GetNoParamsEmptyResponseInternalServerError struct {
}

// NewGetNoParamsEmptyResponseInternalServerError creates GetNoParamsEmptyResponseInternalServerError with default headers values
func NewGetNoParamsEmptyResponseInternalServerError() *GetNoParamsEmptyResponseInternalServerError {

	return &GetNoParamsEmptyResponseInternalServerError{}
}

// WriteResponse to the client
func (o *GetNoParamsEmptyResponseInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
