// Code generated by go-swagger; DO NOT EDIT.

package open

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/seanrmurphy/lambda-swagger-test/models"
)

// GetTestEndpointOKCode is the HTTP code returned for type GetTestEndpointOK
const GetTestEndpointOKCode int = 200

/*GetTestEndpointOK Test Response

swagger:response getTestEndpointOK
*/
type GetTestEndpointOK struct {

	/*
	  In: Body
	*/
	Payload *models.TestResponse `json:"body,omitempty"`
}

// NewGetTestEndpointOK creates GetTestEndpointOK with default headers values
func NewGetTestEndpointOK() *GetTestEndpointOK {

	return &GetTestEndpointOK{}
}

// WithPayload adds the payload to the get test endpoint o k response
func (o *GetTestEndpointOK) WithPayload(payload *models.TestResponse) *GetTestEndpointOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get test endpoint o k response
func (o *GetTestEndpointOK) SetPayload(payload *models.TestResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTestEndpointOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetTestEndpointInternalServerErrorCode is the HTTP code returned for type GetTestEndpointInternalServerError
const GetTestEndpointInternalServerErrorCode int = 500

/*GetTestEndpointInternalServerError General Failure

swagger:response getTestEndpointInternalServerError
*/
type GetTestEndpointInternalServerError struct {
}

// NewGetTestEndpointInternalServerError creates GetTestEndpointInternalServerError with default headers values
func NewGetTestEndpointInternalServerError() *GetTestEndpointInternalServerError {

	return &GetTestEndpointInternalServerError{}
}

// WriteResponse to the client
func (o *GetTestEndpointInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
