// Code generated by go-swagger; DO NOT EDIT.

package open

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/seanrmurphy/lambda-swagger-test/models"
)

// PostBodyParamErrorResponseIMATeapotCode is the HTTP code returned for type PostBodyParamErrorResponseIMATeapot
const PostBodyParamErrorResponseIMATeapotCode int = 418

/*PostBodyParamErrorResponseIMATeapot Error generated when executing API call

swagger:response postBodyParamErrorResponseIMATeapot
*/
type PostBodyParamErrorResponseIMATeapot struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewPostBodyParamErrorResponseIMATeapot creates PostBodyParamErrorResponseIMATeapot with default headers values
func NewPostBodyParamErrorResponseIMATeapot() *PostBodyParamErrorResponseIMATeapot {

	return &PostBodyParamErrorResponseIMATeapot{}
}

// WithPayload adds the payload to the post body param error response i m a teapot response
func (o *PostBodyParamErrorResponseIMATeapot) WithPayload(payload *models.ErrorResponse) *PostBodyParamErrorResponseIMATeapot {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post body param error response i m a teapot response
func (o *PostBodyParamErrorResponseIMATeapot) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostBodyParamErrorResponseIMATeapot) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(418)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostBodyParamErrorResponseInternalServerErrorCode is the HTTP code returned for type PostBodyParamErrorResponseInternalServerError
const PostBodyParamErrorResponseInternalServerErrorCode int = 500

/*PostBodyParamErrorResponseInternalServerError General Failure

swagger:response postBodyParamErrorResponseInternalServerError
*/
type PostBodyParamErrorResponseInternalServerError struct {
}

// NewPostBodyParamErrorResponseInternalServerError creates PostBodyParamErrorResponseInternalServerError with default headers values
func NewPostBodyParamErrorResponseInternalServerError() *PostBodyParamErrorResponseInternalServerError {

	return &PostBodyParamErrorResponseInternalServerError{}
}

// WriteResponse to the client
func (o *PostBodyParamErrorResponseInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
