// Code generated by go-swagger; DO NOT EDIT.

package open

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"github.com/seanrmurphy/lambda-swagger-test/models"
)

// NewPostBodyParamSimpleResponseParams creates a new PostBodyParamSimpleResponseParams object
// no default values defined in spec.
func NewPostBodyParamSimpleResponseParams() PostBodyParamSimpleResponseParams {

	return PostBodyParamSimpleResponseParams{}
}

// PostBodyParamSimpleResponseParams contains all the bound params for the post body param simple response operation
// typically these are obtained from a http.Request
//
// swagger:parameters postBodyParamSimpleResponse
type PostBodyParamSimpleResponseParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*An input JSON object required with this call
	  Required: true
	  In: body
	*/
	BodyParam *models.InputObject
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostBodyParamSimpleResponseParams() beforehand.
func (o *PostBodyParamSimpleResponseParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.InputObject
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("bodyParam", "body", ""))
			} else {
				res = append(res, errors.NewParseError("bodyParam", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.BodyParam = &body
			}
		}
	} else {
		res = append(res, errors.Required("bodyParam", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
