// Code generated by go-swagger; DO NOT EDIT.

package open

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/seanrmurphy/lambda-swagger-test/models"
)

// PostBodyParamComplexResponseOKCode is the HTTP code returned for type PostBodyParamComplexResponseOK
const PostBodyParamComplexResponseOKCode int = 200

/*PostBodyParamComplexResponseOK Successful execution of API call returning complex object

swagger:response postBodyParamComplexResponseOK
*/
type PostBodyParamComplexResponseOK struct {

	/*
	  In: Body
	*/
	Payload *models.ComplexObjectResponse `json:"body,omitempty"`
}

// NewPostBodyParamComplexResponseOK creates PostBodyParamComplexResponseOK with default headers values
func NewPostBodyParamComplexResponseOK() *PostBodyParamComplexResponseOK {

	return &PostBodyParamComplexResponseOK{}
}

// WithPayload adds the payload to the post body param complex response o k response
func (o *PostBodyParamComplexResponseOK) WithPayload(payload *models.ComplexObjectResponse) *PostBodyParamComplexResponseOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post body param complex response o k response
func (o *PostBodyParamComplexResponseOK) SetPayload(payload *models.ComplexObjectResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostBodyParamComplexResponseOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostBodyParamComplexResponseInternalServerErrorCode is the HTTP code returned for type PostBodyParamComplexResponseInternalServerError
const PostBodyParamComplexResponseInternalServerErrorCode int = 500

/*PostBodyParamComplexResponseInternalServerError General Failure

swagger:response postBodyParamComplexResponseInternalServerError
*/
type PostBodyParamComplexResponseInternalServerError struct {
}

// NewPostBodyParamComplexResponseInternalServerError creates PostBodyParamComplexResponseInternalServerError with default headers values
func NewPostBodyParamComplexResponseInternalServerError() *PostBodyParamComplexResponseInternalServerError {

	return &PostBodyParamComplexResponseInternalServerError{}
}

// WriteResponse to the client
func (o *PostBodyParamComplexResponseInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
