// Code generated by go-swagger; DO NOT EDIT.

package open

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/seanrmurphy/lambda-swagger-test/models"
)

// PostBodyParamSimpleResponseOKCode is the HTTP code returned for type PostBodyParamSimpleResponseOK
const PostBodyParamSimpleResponseOKCode int = 200

/*PostBodyParamSimpleResponseOK Test Response

swagger:response postBodyParamSimpleResponseOK
*/
type PostBodyParamSimpleResponseOK struct {

	/*
	  In: Body
	*/
	Payload *models.SimpleMessageResponse `json:"body,omitempty"`
}

// NewPostBodyParamSimpleResponseOK creates PostBodyParamSimpleResponseOK with default headers values
func NewPostBodyParamSimpleResponseOK() *PostBodyParamSimpleResponseOK {

	return &PostBodyParamSimpleResponseOK{}
}

// WithPayload adds the payload to the post body param simple response o k response
func (o *PostBodyParamSimpleResponseOK) WithPayload(payload *models.SimpleMessageResponse) *PostBodyParamSimpleResponseOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post body param simple response o k response
func (o *PostBodyParamSimpleResponseOK) SetPayload(payload *models.SimpleMessageResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostBodyParamSimpleResponseOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostBodyParamSimpleResponseInternalServerErrorCode is the HTTP code returned for type PostBodyParamSimpleResponseInternalServerError
const PostBodyParamSimpleResponseInternalServerErrorCode int = 500

/*PostBodyParamSimpleResponseInternalServerError General Failure

swagger:response postBodyParamSimpleResponseInternalServerError
*/
type PostBodyParamSimpleResponseInternalServerError struct {
}

// NewPostBodyParamSimpleResponseInternalServerError creates PostBodyParamSimpleResponseInternalServerError with default headers values
func NewPostBodyParamSimpleResponseInternalServerError() *PostBodyParamSimpleResponseInternalServerError {

	return &PostBodyParamSimpleResponseInternalServerError{}
}

// WriteResponse to the client
func (o *PostBodyParamSimpleResponseInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
